{{- /*
  Common ConfigMap template for environment variables
*/ -}}
{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common-lib.fullname" . }}
  labels:
    {{- include "common-lib.labels" . | nindent 4 }}

data:
  {{- if .Values.configMap.data }}
  {{- toYaml .Values.configMap.data | nindent 2 }}
  {{- end }}
{{- end }}
